"""Filesystem storage and in-memory registry for uploaded audio files.

Uploads live under ``{data_dir}/audio/{audio_id}/original{ext}`` where
``audio_id`` is a ULID generated by the store. The :class:`AudioFile`
records themselves are kept in memory only: they do not survive a restart,
and files left on disk by a previous run are orphaned (a known limitation
until a persistent registry exists).
"""

import re
import shutil
from pathlib import Path

from ulid import ULID

from straticate.schemas import AudioFile

_SAFE_SUFFIX = re.compile(r"^\.[A-Za-z0-9]{1,10}$")
"""Filename suffixes we are willing to reproduce on disk."""


def _sanitized_suffix(filename: str) -> str:
    """Return a safe lowercase extension for ``filename`` (may be empty).

    The extension is cosmetic only — probing never trusts it — so anything
    that is not a short alphanumeric suffix is dropped entirely.
    """
    suffix = Path(filename).suffix.lower()
    return suffix if _SAFE_SUFFIX.fullmatch(suffix) else ""


class AudioStore:
    """Owns uploaded audio files on disk and their in-memory records.

    **Reading a path never writes to the filesystem.** The store offers two
    path accessors and the difference is the whole point of the split:
    :meth:`original_path` computes a path and touches nothing, while
    :meth:`prepare_original_path` creates the directory because a writer is
    about to use it. Before the split there was only the creating form, so a
    read-only lookup of an upload whose file had vanished
    (:func:`straticate.jobs.resolution.resolve_audio`, documented as pure)
    recreated an empty ``{data_dir}/audio/{audio_id}/`` and *then* reported
    404 — leaving an orphan directory behind on every such probe.

    Args:
        data_dir: Application data directory (``Settings.data_dir``). The
            store writes beneath ``{data_dir}/audio``; directories are
            created lazily, by :meth:`prepare_original_path` only.
    """

    def __init__(self, data_dir: Path) -> None:
        self._audio_root = data_dir / "audio"
        self._records: dict[str, AudioFile] = {}

    def new_id(self) -> str:
        """Generate a new ULID string to identify an upload."""
        return str(ULID())

    def original_path(self, audio_id: str, filename: str) -> Path:
        """Return the on-disk path for an upload's original media.

        **Pure**: the path is computed, and neither it nor its directory is
        created. The returned path may therefore not exist — callers that need
        the file check for it, which is exactly what a reader wants. Use
        :meth:`prepare_original_path` when about to write.

        The file is always named ``original`` plus a sanitized copy of the
        client filename's extension (purely cosmetic — probing never trusts
        it).
        """
        return self._audio_root / audio_id / f"original{_sanitized_suffix(filename)}"

    def prepare_original_path(self, audio_id: str, filename: str) -> Path:
        """Return :meth:`original_path`, with its directory created.

        The one place the store creates directories, called from the upload
        write path. The file itself is not created.
        """
        path = self.original_path(audio_id, filename)
        path.parent.mkdir(parents=True, exist_ok=True)
        return path

    def register(self, record: AudioFile) -> None:
        """Add a validated upload to the registry."""
        self._records[record.id] = record

    def get(self, audio_id: str) -> AudioFile | None:
        """Return the record for ``audio_id``, or ``None`` if unknown."""
        return self._records.get(audio_id)

    def delete(self, audio_id: str) -> bool:
        """Remove the record and its files; return whether it existed."""
        record = self._records.pop(audio_id, None)
        self.remove_files(audio_id)
        return record is not None

    def remove_files(self, audio_id: str) -> None:
        """Delete the upload's directory from disk (no-op if absent).

        Used both by :meth:`delete` and to clean up rejected uploads that
        were never registered.
        """
        directory = self._audio_root / audio_id
        if directory.exists():
            shutil.rmtree(directory, ignore_errors=True)
