"""Filesystem storage and registry for uploaded audio files.

Uploads live under ``{data_dir}/audio/{audio_id}/original{ext}`` where
``audio_id`` is a ULID generated by the store, alongside a sidecar
``{data_dir}/audio/{audio_id}/audio.json`` holding the serialized
:class:`AudioFile` record (feature 056) — the same wire shape the API
returns, no second schema. The sidecar is what makes an upload durable: the
registry is rebuilt from it on the next startup (:meth:`AudioStore.load`),
so an upload from a previous run is not orphaned and a restart does not
invalidate an in-flight job's audio reference.

**Written after the probe, not before.** :meth:`AudioStore.register` is only
ever called once ffprobe has accepted the bytes, so a rejected upload leaves
neither the original file nor a sidecar behind — exactly the invariant the
non-durable version had, just extended to a second file.

**The sidecar write is atomic but not durable.** It goes to a same-directory
``audio.json.{uuid}.tmp`` and is published with :func:`os.replace`, so a
reader never observes a half-written sidecar; there is deliberately no
``fsync`` before the rename. Contrast the model installer
(``straticate.models.installer``), which does fsync before publishing
weights — those take a multi-hundred-megabyte download to reproduce, so the
durability is worth the stall. Losing the *most recent* upload's sidecar in
a power cut is not: the client re-uploads and probing takes a fraction of a
second, so the extra durability was not worth paying for on every upload.
"""

import logging
import os
import re
import shutil
import uuid
from pathlib import Path

from ulid import ULID

from straticate.schemas import AudioFile

logger = logging.getLogger(__name__)

_SAFE_SUFFIX = re.compile(r"^\.[A-Za-z0-9]{1,10}$")
"""Filename suffixes we are willing to reproduce on disk."""

SIDECAR_FILENAME = "audio.json"
"""Name of the durable record sidecar inside ``{audio_id}/``."""


def _sanitized_suffix(filename: str) -> str:
    """Return a safe lowercase extension for ``filename`` (may be empty).

    The extension is cosmetic only — probing never trusts it — so anything
    that is not a short alphanumeric suffix is dropped entirely.
    """
    suffix = Path(filename).suffix.lower()
    return suffix if _SAFE_SUFFIX.fullmatch(suffix) else ""


class AudioStore:
    """Owns uploaded audio files on disk and their records.

    **Reading a path never writes to the filesystem.** The store offers two
    path accessors and the difference is the whole point of the split:
    :meth:`original_path` computes a path and touches nothing, while
    :meth:`prepare_original_path` creates the directory because a writer is
    about to use it. Before the split there was only the creating form, so a
    read-only lookup of an upload whose file had vanished
    (:func:`straticate.jobs.resolution.resolve_audio`, documented as pure)
    recreated an empty ``{data_dir}/audio/{audio_id}/`` and *then* reported
    404 — leaving an orphan directory behind on every such probe.

    **Records are cached in memory and mirrored to disk.** :meth:`register`
    keeps the ``dict`` this class always had (so :meth:`get` stays a
    zero-I/O lookup) and additionally writes the ``audio.json`` sidecar
    described in the module docstring. Nothing repopulates the cache except
    :meth:`register` and :meth:`load` — the explicit, startup-time sweep
    that rebuilds it from whatever sidecars survived the previous run.

    Args:
        data_dir: Application data directory (``Settings.data_dir``). The
            store writes beneath ``{data_dir}/audio``; directories are
            created lazily, by :meth:`prepare_original_path` and
            :meth:`register` only.
    """

    def __init__(self, data_dir: Path) -> None:
        self._audio_root = data_dir / "audio"
        self._records: dict[str, AudioFile] = {}
        self._pending: set[str] = set()

    def new_id(self) -> str:
        """Generate a new ULID string to identify an upload."""
        return str(ULID())

    def original_path(self, audio_id: str, filename: str) -> Path:
        """Return the on-disk path for an upload's original media.

        **Pure**: the path is computed, and neither it nor its directory is
        created. The returned path may therefore not exist — callers that need
        the file check for it, which is exactly what a reader wants. Use
        :meth:`prepare_original_path` when about to write.

        The file is always named ``original`` plus a sanitized copy of the
        client filename's extension (purely cosmetic — probing never trusts
        it).
        """
        return self._audio_root / audio_id / f"original{_sanitized_suffix(filename)}"

    def prepare_original_path(self, audio_id: str, filename: str) -> Path:
        """Return :meth:`original_path`, with its directory created.

        The one place the store creates directories, called from the upload
        write path. The file itself is not created.

        Creating the directory also **reserves** ``audio_id`` as a pending
        upload (:meth:`pending_ids`) until :meth:`register` or
        :meth:`remove_files` resolves it. That reservation is what keeps
        ``POST /system/prune`` from deleting an upload that is still
        streaming: between this call and ``register``, the directory holds
        real bytes but no record, which is precisely feature 059's definition
        of an orphan. Nothing else in the application can tell the two apart
        from the filesystem alone — a 40-minute upload of a large file looks,
        for 40 minutes, exactly like the leftovers of one that died.
        """
        path = self.original_path(audio_id, filename)
        path.parent.mkdir(parents=True, exist_ok=True)
        self._pending.add(audio_id)
        return path

    def register(self, record: AudioFile) -> None:
        """Add a validated upload to the registry, durably.

        Persists the ``audio.json`` sidecar (see the module docstring) beside
        the already-written original, atomically: a temp file in the same
        directory, renamed into place with :func:`os.replace`. No ``fsync`` —
        the trade-off is documented on the module.

        Called only after the upload has already been probed successfully
        (``api/audio.py``), so a rejected upload never reaches here and never
        leaves a sidecar behind, matching its existing no-file guarantee.

        The sidecar is written **before** the in-memory record is assigned
        (review finding): a failed write raises out of here with the registry
        untouched, so the caller's cleanup path removes the files and the 500
        the client sees agrees with what the server holds. The old order left
        a live, servable record whose upload had "failed" — and, after a
        restart, an orphan.
        """
        directory = self._audio_root / record.id
        directory.mkdir(parents=True, exist_ok=True)
        sidecar = directory / SIDECAR_FILENAME
        tmp = directory / f"{SIDECAR_FILENAME}.{uuid.uuid4().hex}.tmp"
        tmp.write_text(record.model_dump_json())
        os.replace(tmp, sidecar)
        self._records[record.id] = record
        # The upload is no longer pending: it now has a record, which is what
        # every other reader (including prune) recognises it by.
        self._pending.discard(record.id)

    def load(self) -> None:
        """Rebuild the registry from sidecars a previous run left on disk.

        A **read-only** sweep of ``{data_dir}/audio``: it only ever populates
        the in-memory cache, never writes, repairs or deletes anything on
        disk — an orphan is left exactly as found, for a later feature to
        surface or prune (see the feature 056 design notes).

        Call this once per *running* application, after logging is
        configured — i.e. from the lifespan, the way
        :class:`~straticate.system.DeviceDetector` is warmed there rather
        than from :func:`~straticate.main.create_app`. ``create_app`` runs at
        **import** for ``straticate.main``'s module-level ``app`` (the
        ``uvicorn straticate.main:app`` entry path), before either entry path
        has configured logging, so a warning logged from ``__init__`` would
        print bare with no timestamp or logger name — precisely the trap the
        device probe fell into before feature 029 moved it out of
        ``create_app``. This method is therefore never called from
        :meth:`__init__`.

        For each ``{audio_id}`` subdirectory of ``{data_dir}/audio``:

        - a valid sidecar *and* its original media file are both present →
          the record is restored;
        - only one of the two is present → skipped silently (an orphan);
        - the sidecar exists but fails to parse (corrupt JSON, or JSON that
          no longer validates as :class:`AudioFile`) → logged at WARNING and
          skipped — one bad record must never fail application startup;
        - a stray ``audio.json.{uuid}.tmp`` left by an interrupted
          :meth:`register` — e.g. a crash between the write and the rename —
          is ignored: it is not named ``audio.json``, so nothing here looks
          at it.

        The directory name is the ground truth this sweep walks. A sidecar
        whose own ``id`` field disagrees with the directory it lives in
        (which :meth:`register` never produces — only a hand-edit or
        cross-directory copy can) is **skipped with a warning**, exactly like
        a corrupt one: restoring it under either id would serve a record
        whose links point at the other (review finding).
        """
        if not self._audio_root.is_dir():
            return
        try:
            directories = sorted(self._audio_root.iterdir())
        except OSError as exc:
            # An unreadable audio root must degrade like one bad record does,
            # not fail startup: the sweep's whole contract is that nothing on
            # this path can stop the application from booting.
            logger.warning("Cannot read the audio directory %s: %s", self._audio_root, exc)
            return
        for directory in directories:
            if not directory.is_dir():
                continue
            audio_id = directory.name
            sidecar = directory / SIDECAR_FILENAME
            if not sidecar.is_file():
                continue
            try:
                record = AudioFile.model_validate_json(sidecar.read_bytes())
            except (OSError, ValueError) as exc:
                logger.warning("Skipping unreadable audio record %r: %s", audio_id, exc)
                continue
            if record.id != audio_id:
                logger.warning(
                    "Skipping audio record %r: its sidecar names a different id %r",
                    audio_id,
                    record.id,
                )
                continue
            if not self.original_path(audio_id, record.filename).is_file():
                continue
            self._records[audio_id] = record

    def get(self, audio_id: str) -> AudioFile | None:
        """Return the record for ``audio_id``, or ``None`` if unknown."""
        return self._records.get(audio_id)

    def ids(self) -> list[str]:
        """Return the IDs of every currently registered upload.

        A read-only view of the registry, in registration order (the
        ``dict``'s own iteration order). Feature 059's disk-usage walker uses
        this to tell a live upload directory from an orphan without handing
        the store — or any other application state — to a function that is
        otherwise a pure filesystem read; it takes the ID collection, not
        the store.
        """
        return list(self._records)

    def pending_ids(self) -> list[str]:
        """Return the IDs of uploads that are being written but not yet registered.

        An upload occupies ``{data_dir}/audio/{audio_id}/`` from
        :meth:`prepare_original_path` until :meth:`register` — the whole
        duration of the multipart stream and the ffprobe that follows it —
        and during that window it has a directory and no record. Feature
        059's classification calls a directory with no record an *orphan*,
        which is right for what it does (report) and dangerous for what
        feature 060 does (delete): pruning orphans would remove the file a
        client is still uploading, and the upload would then fail on a
        ``os.replace`` into a directory that no longer exists.

        ``POST /system/prune`` therefore treats these IDs as live. The
        reservation is dropped by :meth:`register` (it has a record now) and
        by :meth:`remove_files` (its files are gone) — which
        ``api/audio.py`` calls on **every** failure path, so no crash between
        the two leaks a permanent exemption. A process that dies mid-upload
        leaves the directory a genuine orphan, and the next process, with an
        empty reservation set, prunes it exactly as it should.
        """
        return sorted(self._pending)

    def delete(self, audio_id: str) -> bool:
        """Remove the record and its files; return whether it existed."""
        record = self._records.pop(audio_id, None)
        self.remove_files(audio_id)
        return record is not None

    def remove_files(self, audio_id: str) -> None:
        """Delete the upload's directory from disk (no-op if absent).

        Used both by :meth:`delete` and to clean up rejected uploads that
        were never registered. Also releases any :meth:`pending_ids`
        reservation: the files this protected are gone, so protecting the ID
        further would exempt an empty directory from pruning forever.
        """
        self._pending.discard(audio_id)
        directory = self._audio_root / audio_id
        if directory.exists():
            shutil.rmtree(directory, ignore_errors=True)
